config/routes.rb
Rails.application.routes.draw do
  resources :companies
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :posts
  resource :comments
  resources :categories
  resources :subscriptions
  resources :people, :path => 'profile'
  root :to => "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_and_belongs_to_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  mount_uploader :image, ImageUploader
  #belongs_to :post
  #belongs_to :user

  def user
    User.find(self.user_id)
  end

  def post
    Post.find(self.post_object_id)
  end

end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :posts, :as => :postable
end

app/models/person.rb
class Person < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    include Mongoid::Document
    include Mongoid::Timestamps::Created
    include Mongoid::Timestamps::Updated
    include Mongoid::Attributes::Dynamic
    # rolify
    # validates :title, :content, :presence => true
    # validates :title, :content, :tags, :presence => true

    #embeds_many :comments
    # has_many :comments

    #has_and_belongs_to_many :categories

    #belongs_to :postable, polymorphic: true

    #accepts_nested_attributes_for :postable

    def user
        User.find(self.postable_id)
    end

    def company
        Company.find(self.postable_id)
    end

    def categories
        Category.where(id: self.category_ids)
    end

    def comments
        Comment.where(post_object_id: self._id.to_s)
    end

end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :subscriber, :foreign_key => "user_subs_id", :class_name => "User"
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :person
  has_many :subscriptions
  has_many :users, through: :subscriptions
  has_many :companies
  has_many :posts, :as => :postable

  accepts_nested_attributes_for :person
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!

  def index
    @profile = current_user
  end

  def update
    respond_to do |format|
      if current_user.person.update(person_params)
        format.html { redirect_to people_path, notice: 'Avatar was successfully updated.' }
      end
    end
  end

  private
    def person_params
      params.require(:person).permit(:avatar)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  load_and_authorize_resource
  skip_authorize_resource :only => :new

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment  = Comment.new
    @sub_user = Subscription.new
  end

  # GET /posts/new
  def new
    @post = Post.new
    @categories = Category.all
    @companies = current_user.companies
  end

  # GET /posts/1/edit
  def edit
    @categories = Category.all
    @companies = current_user.companies
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    if (post_params[:postable_type] == 'Company')
       @post[:postable_id] = params[:company_id]
       # @post.postable_id = params[:company_id]
    else
      @post[:postable_id] = current_user.id
      # @post.postable_id = current_user.id
    end

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end


  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :tags, {:category_ids => []}, :postable_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">

  <%= link_to 'Home', posts_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          User
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <%= link_to 'Profile', people_path, class: "dropdown-item" %>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <li class="nav-item">
        <% if can? :create, Category %>
          <%= link_to 'Categories', categories_path, class: 'nav-link' %>
        <% end %>
      </li>
      <li class="nav-item">
        <% if can? :create, Company %>
          <%= link_to 'Companies', companies_path, class: 'nav-link' %>
        <% end %>
      </li>
      <li class="nav-item">
        <% if can? :create, Subscription %>
          <%= link_to 'Followers', subscriptions_path, class: 'nav-link' %>
        <% end %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render('layouts/navbar') %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>